### Numpy Array Operations

In [1]:
import numpy as np

Let's begin by importing Numpy and listing out the functions covered in this notebook.

# List of functions explained 
function1 = np.empty

function2 = np.copyto

function3 = np.equal

function4 = np.sort

function5 = bitwise

## Function 1 - np.empty

This function helps you to create numpy arrays without initialize the entry of given shapes and types, it's like np.zeros but it's quite faster

In [2]:
# Example 1 - working
np.empty(2, dtype=int)


NameError: name 'np' is not defined

Created random (2,0) array of type int

In [5]:
# Example 2 - working
np.empty((3,5), dtype=float, order = 'C')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

You can define the size of the array

In [1]:
# Example 3 - not working
np.empty(2, dtype='datetime64')

NameError: name 'np' is not defined

In this example I tried to make an numpy array of datetime and it gave error,
In order to fix it we have to define the country of the datetime, like this:
### np.empty(2, dtype='datetime64[us]')

It's really useful function we can use it when we want to product to arrays with one have a value of zeroes

## Function 2 Copyto

this function copies values from np array to another one, the formula is

numpy.copyto(dst, src, casting='same_kind', where=True)

In [9]:
# Function 1 working
gfg = np.array([1, 2, 3])
print(gfg)
geeks = [4, 5, 6]
print(geeks)      
np.copyto(gfg, geeks)
print(gfg)

[1 2 3]
[4, 5, 6]
[4 5 6]


In this example we can see that with the help of numpy.copyto() method we are making the copy of an elements in a destination array.

In [10]:
# Function 2 working
gfg = np.array([[1, 2, 3], [4, 5, 6]])
geeks = [[4, 5, 6], [7, 8, 9]]
np.copyto(gfg, geeks)
print(gfg)


[[4 5 6]
 [7 8 9]]


We can copy list of arrays as well

In [17]:
#Function 3 not working
gfg = np.array([1, 2, 3, 4])
geeks = [4, 5, 6]
np.copyto(gfg, geeks)


ValueError: could not broadcast input array from shape (3,) into shape (4,)

Both arrays should have the same shape

## Function 3 - Np.equal

Compares whether the 2 arrays values are equal

In [32]:
#Function 1 working
a = np.equal([1., 2.], [1., 3.])
print("Check to be Equal : \n", a, "\n")

b = np.equal([1, 2], [[1, 3],[1, 2]])
print("Check to be Equal : \n", b, "\n")


Check to be Equal : 
 [ True False] 

Check to be Equal : 
 [[ True False]
 [ True  True]] 



In the second example the check ran to compare values with the first array

In [39]:
#Function 2 working
a = np.array([6+7j, 2])
b = np.array([1,2])

d = np.equal(a, b)
print("Comparing complex with int using .equal() : \n ", d)


Comparing complex with int using .equal() : 
  [False  True]


 Comparing data-type using .equal() function

In [40]:
#Function 3 not working
a = np.equal(['1.', 2.], [1., 3.])
print("Check to be Equal : \n", a, "\n")


UFuncTypeError: ufunc 'equal' did not contain a loop with signature matching types (<class 'numpy.dtype[str_]'>, <class 'numpy.dtype[float64]'>) -> None

The 2 arrays must have the same class

## Function 4 - numpy.sort()

Return a sorted copy of an array.



In [59]:
#Function 1 working
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)        
 

Along first axis : 
 [[10  1]
 [12 15]]


sorts the array on the columns axis

In [61]:
#Function 2 working
a = np.array([['a', 15], ['b', 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)        
 

Along first axis : 
 [['a' '1']
 ['b' '15']]


It can sort strings as well

In [63]:
#Function 3 not working
a = np.array([['a', 15], ['b', 1]])
arr1 = np.sort(a, axis = 2)        
print ("Along first axis : \n", arr1)        
 

AxisError: axis 2 is out of bounds for array of dimension 2

Axis should be 1 or 0

## Function 5 - bitwise

There are functions to convert the elements into their binary representation and then apply operations on the bits.

In [71]:
#Function 1 working
a=10
b=11
print(bin(a))
print(bin(b))
np.bitwise_and(a,b)

0b1010
0b1011


10

and operator to 10 binary and 11 binary

In [72]:
#Function 2 working
a=15
b=35
print(bin(a))
print(bin(b))
np.bitwise_or(a,b)

0b1111
0b100011


47

or operator to 15 binary and 35 binary